### ISSUE TITLE
unable to locate 'chillis.csv' file

### ISSUE THREAD

**Issue by jamie-chiu** [PSY-504-Labs/lab-1-robust-methods-jamie-chiu#2]
Could you please post the updated link to the 'chillis.csv' file? I was not sure where the link was posted. Thank you!

**Comment by jgeller112** [comment]
I posted the updated link on Canvas (it is in the newer version of the Lab 1 assignment).  It is also here: https://raw.githubusercontent.com/jgeller112/psy504-advanced-stats/main/slides/03-Robust_Methods/data/chillis.csv
